.gitignore
gulpfile.js
package-lock.json
package.json
package/.gitignore
tasks/gulp/build.js
tasks/gulp/clean.js

Adds two new gulp tasks to copy govuk-frontend.
We do intend on version controlling `govuk-frontend` because we would like our frontend applications to rely purely on this frontend and not have directly importing various different versions. It will also help us ensure that other custom components will work with specific versions of `govuk-frontend` without relying on updating the various frontend applications to those specific versions.
`npm run build`

Import and use govuk-frontend

---

package-lock.json
package.json

- Renames the repo
- Prepares package.json by making this private. We only want to be able to publish the package directory and version that directory

Rename repo and prepare package.json

---

LICENCE
README.md

Adds the MIT Licence as per our other libraries (see dmutils example: https://github.com/alphagov/digitalmarketplace-utils/blob/master/LICENCE).

Move LICENCE info into dedicated file

---

bin/release-to-branch.sh

Unfortunately, we could not completely use GOV.UK Frontend code without
a small modification.
The issue was that GOV.UK Frontend versions everything inside their `package/`
folder. This meant that the release-to-branch.sh was pushing up package/govuk-frontend
to githube. However, in our case we are not interested in versioning our compiled
code because the compiled code is only used when we publish a release.
So to get this to work we force add `package/` just for the new pre-release
branch we use for testing.

Fixes release to branch feature

---

.gitignore
CHANGELOG.md
bin/pre-release.sh
gulpfile.js
package-lock.json
package.json
src/digitalmarketplace/templates/errors/400.html
src/digitalmarketplace/templates/errors/403.html
src/digitalmarketplace/templates/errors/404.html
src/digitalmarketplace/templates/errors/410.html
src/digitalmarketplace/templates/errors/500.html
tasks/gulp/build.js

Adds error page templates.
These use GOV.UK Frontend but apart from that the content is identical to the existing templates in digitalmarketplace-frontend-toolkit.
Will help to reduce the number of files in this PR.
https://github.com/alphagov/digitalmarketplace-admin-frontend/pull/560
Ticket: https://trello.com/c/pT5lRLOG

Add error templates

---

scripts/tag_latest_version.sh

https://trello.com/c/bzsVPMU3/57-jenkins-job-to-auto-tag-digitalmarketplace-govuk-frontend-releases
For use by a (shortly-to-be-created) Jenkins job (similar to the [FE toolkit auto-tag job](https://github.com/alphagov/digitalmarketplace-jenkins/blob/master/job_definitions/toolkit.yml)) which polls for scm changes every 2 minutes. We currently use this system to auto tag our other python and FE toolkit libraries. [See for yourself just how much I've copied this script from the latter.](https://github.com/alphagov/digitalmarketplace-frontend-toolkit/blob/master/pages_builder/tag_latest_version.sh) 😸
This will remove a step (number 15) from [the manual publishing process](https://github.com/alphagov/digitalmarketplace-govuk-frontend/blob/master/docs/publishing.md). 
The tag version number …

Adds script to tag repo releases

---

.travis.yml

Travis runs `npm test` by default but not build script. Github tests
were runing build and then test and passing where as Travis was failing
because build script had not been run.

Run build task on Travis CI

---

CHANGELOG.md
src/digitalmarketplace/templates/errors/400.html
src/digitalmarketplace/templates/errors/403.html
src/digitalmarketplace/templates/errors/404.html
src/digitalmarketplace/templates/errors/410.html
src/digitalmarketplace/templates/errors/500.html

Error pages did not have their content centrally aligned.
ticket: https://trello.com/c/T9hBnYM5

Fix layout issues with error pages

---

CHANGELOG.md
package/package.json

🔧 Fixes:
- Fix layout issues with error pages
Error pages' content was not centrally aligned.
Check frontend app `config.py` includes `os.path.join(repo_root, 'node_modules', 'digitalmarketplace-govuk-frontend', 'digitalmarketplace', 'templates'),` to lookup the error templates
Make sure `base_page.html` is using `mainContent` and `pageTitle` blocks
([PR #23](https://github.com/alphagov/digitalmarketplace-govuk-frontend/pull/23))

Release v0.2.1

---

.gitignore
CHANGELOG.md
config/jest-setup.js
config/paths.test.json
lib/axe-helper.js
lib/helper-functions.js
lib/jest-helpers.js
package-lock.json
package.json
src/digitalmarketplace/components/footer/__snapshots__/template.test.js.snap
src/digitalmarketplace/components/footer/footer.yaml
src/digitalmarketplace/components/footer/macro.njk
src/digitalmarketplace/components/footer/template.njk
src/digitalmarketplace/components/footer/template.test.js
tasks/gulp/build.js
tasks/gulp/clean.js

Ticket: https://trello.com/c/OYUBf016/
Inherits markup and styling from GOV.UK Frontend but allows us to pass in a standard set of options that will be used across all our frontend applications. 
If you would like to test the component you can run this locally
`npm install --save alphagov/digitalmarketplace-govuk-frontend#def9e5b` and the frontend will need `dmutils v48.8.0` before following the directions in the [CHANGELOG](https://github.com/alphagov/digitalmarketplace-govuk-frontend/pull/21/files#diff-4ac32a78649ca5bdd8e0ba38b7006a1e).

New component: Digital Marketplace Footer component

---

CHANGELOG.md
app/assets/scss/app.scss
src/digitalmarketplace/_all.scss
src/digitalmarketplace/components/header/__snapshots__/template.test.js.snap
src/digitalmarketplace/components/header/_header.scss
src/digitalmarketplace/components/header/header.yaml
src/digitalmarketplace/components/header/macro.njk
src/digitalmarketplace/components/header/template.njk
src/digitalmarketplace/components/header/template.test.js

We would have just used GOV.UK Frontend header component but we needed
to customize it specifically for Digital Martketplace.
1. Navigation links position - we needed to the style of all the applications
to look consistent while we roll out govuk-frontend. Therefore we needed
the navigation to be right-aligned and the service name to be positioned
next to the crown.
2. Admin frontend - For Admin frontend we wanted to use a different header so
users could see they were no longer in the main application. To do this we 
added `Admin` to the end of the product name and there is still the red border
1. Import the component
2. Call the component using 
```
{{ dmHeader({ 
"role": current_user|default(None)
}) }}
```
3. For Admin frontend use 
```
{{ dmHeader({
"isAdmin": "true", 
"role": …
```

New component: Digital Marketplace Header component

---

package-lock.json
package.json

We are not currently using this anywhere, we should remove it.

Remove gulp-rename

---

src/digitalmarketplace/components/header/__snapshots__/template.test.js.snap
src/digitalmarketplace/components/header/_header.scss
src/digitalmarketplace/components/header/template.njk
src/digitalmarketplace/components/header/template.test.js

`app` should only be used by the frontend application itself and not
any component library. To be consistent, I have corrected this by replacing
`app-` prefix with `dm-` prefix. This should not break anything as this
component has not been officially released or used in any of our
applicaitons

fix header class prefix from app to dm

---

CHANGELOG.md
package/package.json

🔧 Fixes:
- Update release script
We changed the release process but did not update the script as a result we had
unpublish v0.3.0 from npm.
([PR #42](https://github.com/alphagov/digitalmarketplace-govuk-frontend/pull/42))

Release v0.3.1

---

src/digitalmarketplace/components/alert/alert.yaml

Correct typo, alert type `alert` is actually `error`.

Fix readme for alert component

---

src/digitalmarketplace/components/footer/__snapshots__/template.test.js.snap
src/digitalmarketplace/components/footer/template.njk

@NoraGDS pointed out that `A to Z` is more readable and accessible than `A-Z`.
Ticket: https://trello.com/c/i4eJBbNC/274-replace-content-supplier-a-z-with-supplier-a-to-z

Change link to supplier A to Z

---

CHANGELOG.md
package/package.json

🔧 Fixes:
- Change link text for G-Cloud supplier A to Z link in footer
([PR 55](https://github.com/alphagov/digitalmarketplace-govuk-frontend/pull/55))

Release 0.4.1

---

CHANGELOG.md
src/digitalmarketplace/components/header/template.njk

Nunjucks macro option `productUrl` should be `homepageUrl`.
This actually doesn't matter because the default for `homepageUrl` is `/`, which is what we wanted; best to have it right anyway :)

Fix option name in header component

---

CHANGELOG.md
src/digitalmarketplace/components/cookie-banner/__snapshots__/template.test.js.snap
src/digitalmarketplace/components/cookie-banner/cookie-banner.js
src/digitalmarketplace/components/cookie-banner/cookie-banner.test.js
src/digitalmarketplace/components/cookie-banner/cookie-banner.yaml
src/digitalmarketplace/components/cookie-banner/template.njk
src/digitalmarketplace/helpers/cookie/cookie-functions.js

https://trello.com/c/hGlNERQ6/294-3-cookie-settings-page-incl-analytics-roll-out
Small Cookie Banner fixes:
- We should use `dm_cookies_policy` to be in line with our other custom cookies
- There are two cookie URLs: one for the Cookie Settings page (`/user/cookies` - User FE) and one for detailed cookie info (`/cookies` - Buyer FE). I've amended the template to make this clearer.
- The cookie banner should not be displayed on the Cookie Settings page, as then there would be two forms on the page, which could be confusing. It's fine to have the banner on the Cookie Info page however, where there's no form. However, this check will be done by the Cookie Settings page  itself, not the banner code.

Add 'dm' namespacing to our cookies

---

CHANGELOG.md
src/digitalmarketplace/all.js
src/digitalmarketplace/components/cookie-settings/README.md
src/digitalmarketplace/components/cookie-settings/cookie-settings.js
src/digitalmarketplace/components/cookie-settings/cookie-settings.test.js

https://trello.com/c/hGlNERQ6/294-3-cookie-settings-page-incl-analytics-roll-out
Based largely on the equivalent Notify code (https://github.com/alphagov/notifications-admin/pull/3238).
Follows the structure, initialisation and import patterns of the Cookie Banner component. However, this component is Javascript-only - there's no template to include or test. As such the jest tests are limited to asserting stubbed out methods. Detailed behaviour tests for integration with the form itself will be added in the User FE.
See the component's README file for expected behaviour of this code.

Cookie settings page JS

---

CHANGELOG.md
package/package.json

- New component: Cookie settings page javascript
- Allows a user to set their analytics cookie preferences
([PR #60](https://github.com/alphagov/digitalmarketplace-govuk-frontend/pull/60))
🔧 Fixes:
- Use dm_cookies_policy to be in line with our other custom cookies
- Use template parameters for Cookie Settings URL and Cookie Info URL
- Banner should not be displayed on the Cookie Settings page
- Prefix custom CSS classes with 'dm-'
([PR #62](https://github.com/alphagov/digitalmarketplace-govuk-frontend/pull/62))

Release 0.6.0

---

CHANGELOG.md
src/digitalmarketplace/components/cookie-settings/cookie-settings.js
src/digitalmarketplace/components/cookie-settings/cookie-settings.test.js

https://trello.com/c/0PYrZ8Yy/323-cookie-settings-form-defaults-to-no-even-if-preference-set-to-yes
The Cookie Settings form was always defaulting to 'No', as the existing consent cookie value was not being parsed correctly (the test for it was returning a mocked response that was already a JSON object).
There is already a helper function to solve this very problem, `getConsentCookie`, which we weren't using 🤦‍♀

Parse consent cookie value as JSON

---

CHANGELOG.md
package/package.json

🔧 Fixes:
- Fix pre-filled values on the Cookie Settings form, by parsing dm_cookies_policy as a JSON object.
([PR #67](https://github.com/alphagov/digitalmarketplace-govuk-frontend/pull/67))

Release 0.6.1

---

CHANGELOG.md
src/digitalmarketplace/components/analytics/init.js
src/digitalmarketplace/components/analytics/init.test.js

Quick fix: the GOV.UK tracking ID was being used instead of the Digital Marketplace ID.

Fix tracking ID fix

---

CHANGELOG.md
package/package.json

🔧 Fixes:
- Fix incorrect Google Analytics tracking ID.
([PR #70](https://github.com/alphagov/digitalmarketplace-govuk-frontend/pull/70))

Release 0.6.2

---

CHANGELOG.md
src/digitalmarketplace/all.js

https://trello.com/c/feRizfhu/326-analytics-tracking-id-fix
As per Notify's initialisation code: https://github.com/alphagov/notifications-admin/blob/master/app/assets/javascripts/main.js#L6

Initialise Analytics if consent cookie is present

---

CHANGELOG.md
src/digitalmarketplace/components/analytics/analytics.js
src/digitalmarketplace/components/analytics/analytics.test.js
src/digitalmarketplace/components/analytics/init.js
src/digitalmarketplace/components/analytics/init.test.js

Looking at the Google Analytics documentation[[1], [2]] and examples from Notify[[3]] and our previous code[[4]] I don't think this is needed.
[1]: https://developers.google.com/analytics/devguides/collection/analyticsjs/field-reference#name
[2]: https://developers.google.com/analytics/devguides/collection/analyticsjs/creating-trackers
[3]: https://github.com/alphagov/notifications-admin/blob/master/app/assets/javascripts/analytics/analytics.js
[4]: https://github.com/alphagov/digitalmarketplace-frontend-toolkit/blob/master/toolkit/javascripts/analytics/_register.js

Remove tracker name from Google Analytics create command event

---

CHANGELOG.md
src/digitalmarketplace/components/footer/__snapshots__/template.test.js.snap
src/digitalmarketplace/components/footer/template.njk

The footer on the Digital Marketplace is showing the link "Applying to sell on the G-Cloud *frameword*"
I assume this is a typo - this PR fixes it

Fix "frameword" typo in footer

---

CHANGELOG.md
src/digitalmarketplace/components/analytics/analytics.js
src/digitalmarketplace/components/analytics/analytics.test.js
src/digitalmarketplace/components/analytics/init.js
src/digitalmarketplace/components/analytics/init.test.js
src/digitalmarketplace/components/analytics/pii.js
src/digitalmarketplace/components/analytics/pii.test.js
src/digitalmarketplace/components/cookie-banner/cookie-banner.test.js

https://trello.com/c/hRRSka2u/5-re-enable-cross-domain-tracking-3
Copies across cross-domain tracking code (and tests!) from the old Frontend Toolkit, with some minor adjustments to fit the new linter/testing style.
I've updated the flaky test in `cookie-banner.test.js` with the expected `gat_govuk_shared` cookie, and removed the `skip` - let's see if Travis likes it.

Cross domain tracking code

---

CHANGELOG.md
package/package.json

https://trello.com/c/hRRSka2u/5-re-enable-cross-domain-tracking-3
- Adding gov.uk cross-domain tracking to Digital Marketplace analytics, based on the old [Frontend Toolkit analytics code](https://github.com/alphagov/digitalmarketplace-frontend-toolkit/blob/master/toolkit/javascripts/analytics/_register.js#L16).
- Includes function calls to strip personal data from both DMP analytics events and cross domain tracker events.

Release 0.8.0

---

CHANGELOG.md
src/digitalmarketplace/helpers/cookie/cookie-functions.js
src/digitalmarketplace/helpers/cookie/cookie-functions.test.js

https://trello.com/c/hRRSka2u/5-re-enable-cross-domain-tracking-3
Spotted a bug where the new cross domain tracking cookie (`gat_govuk_shared`) was not being deleted when the user changed their analytics cookie preferences on the settings page to 'Off'.
Also adds some basic test coverage for the cookie helper functions where this bit of logic lives.

Fix cross domain tracking when changing cookie settings

---

CHANGELOG.md
src/digitalmarketplace/components/banner/__snapshots__/template.test.js.snap
src/digitalmarketplace/components/banner/_banner.scss
src/digitalmarketplace/components/banner/banner.yaml
src/digitalmarketplace/components/banner/template.njk

While having a conversation with @domoscargin I realised that our banner examples could be more representative of how they are to be used on the site.
While doing *that*, I discovered that the link text was wrong :laughing:

Add representative banner examples

---

CHANGELOG.md
src/digitalmarketplace/components/alert/__snapshots__/template.test.js.snap
src/digitalmarketplace/components/alert/template.njk
src/digitalmarketplace/components/banner/__snapshots__/template.test.js.snap
src/digitalmarketplace/components/banner/template.njk

https://trello.com/c/FR1sGM3j/22-2-fix-axe-errors-in-digitalmarketplace-govuk-frontend
The Alert and Banner components fail [this rule](https://dequeuniversity.com/rules/axe/3.5/region)
Partly, this is because when the test templates are rendered, cheerio is wrapping them with some boilerplate, but not a `<main>` or other recognised ARIA landmark.
However, this gives us the chance to improve the component accessibility and pass the tests even with the poor wrap.
* Follow GOV.UK [Error Summary](https://design-system.service.gov.uk/components/error-summary/) and set `role="alert"` and `tabindex="-1"`. Set the `aria-label` to be the same as the title. Future improvement may be to generate an ID for the heading and use `aria-labelledby` instead.
* Since banners are not live-regions, we can …

Fix banner and alert failing axe region rule

---

CHANGELOG.md
src/digitalmarketplace/components/cookie-settings/cookie-settings.js
src/digitalmarketplace/components/cookie-settings/cookie-settings.test.js

this is part of https://trello.com/c/btdB5xBK/98-missing-contextual-error-messaging-on-cookie-settings-page
adds inline error message as per [design system error message component](https://design-system.service.gov.uk/components/error-message/)

add and remove inline error message

---

README.md
bin/release-to-branch.sh
bin/release.sh
gulpfile.js
package.json
tasks/gulp/compile-assets.js

This change should make it easier to test changes to digitalmarketplace-govuk-frontend locally; now running `gulp build` will always create everything needed for a package, so you can run
$ npm run build
$ cd ../digitalmarketplace-user-frontend
$ npm install ../digitalmarketplace-govuk-frontend/package
to use your local copy of digitalmarketplace-govuk-frontend.

Change gulp compile to always compile for both development and publishing

---

.gitignore
CHANGELOG.md
app/app.js
app/assets/scss/app.scss
app/views/layouts/all-components.njk
app/views/layouts/component.njk
app/views/macros/showExamples.njk
config/paths.test.json
lib/jest-helpers.js
src/digitalmarketplace/components/alert/_alert.scss
src/digitalmarketplace/components/banner/_banner.scss
src/digitalmarketplace/components/cookie-banner/_cookie-banner.scss
src/digitalmarketplace/components/footer/template.njk
src/digitalmarketplace/components/header/_header.scss
src/digitalmarketplace/components/header/template.njk
src/digitalmarketplace/components/list-input/_list-input.scss
src/digitalmarketplace/components/list-input/template.njk
src/template.njk
tasks/gulp/clean.js
tasks/gulp/copy.js

https://trello.com/c/qqAnOWNw/146-migrate-digitalmarketplace-govuk-frontend-to-use-govuk-frontend-v3
I think we want the location of govuk-frontend components and styles to be consistent with GOV.UK Design System and govuk-frontend v3.
This commit changes the location to be `govuk/`, rather than `govuk-frontend/`.
This means that any apps that migrate to accomodate this change won't then need to change paths again when migrating to govuk-frontend v3.

Move govuk-frontend src from govuk-frontend to govuk

---

CHANGELOG.md
package/package.json

💥 Breaking changes:
- Move Digital Marketplace files around
We've moved some files around so their locations are consistent with govuk-frontend.
- The Digital Marketplace JavaScript file is now found at `digitalmarketplace-govuk-frontend/digitalmarketplace/all.js`
- The Digital Marketplace Sass file is now found at `digitalmarketplace-govuk-frontend/digitalmarketplace/all.scss`
You must change how you copy or import Digital Marketplace JavaScript:
```
// to copy Digital Marketplace JavaScript using gulp-include
//= require ../../../node_modules/digitalmarketplace-govuk-frontend/digitalmarketplace/all.js
```
You may need to change how you import Digital Marketplace Sass:
```
@import "node_modules/digitalmarketplace-govuk-frontend/digitalmarketplace/all"
```
([PR …

Release 1.0.0

---

CHANGELOG.md
src/digitalmarketplace/components/cookie-banner/__snapshots__/template.test.js.snap
src/digitalmarketplace/components/cookie-banner/template.njk

The cookie banner is a `region` but has no label, so fails WCAG 1.3.1.
Giving it an `aria-label` fixes this.

Add aria-label to cookie banner

---

CHANGELOG.md
package/package.json

🔧 Fixes:
- The cookie banner component now has an `aria-label` property [PR #161](https://github.com/alphagov/digitalmarketplace-govuk-frontend/pull/161)
- The alert and banner components no longer have a focusable state [PR #158](https://github.com/alphagov/digitalmarketplace-govuk-frontend/pull/158)

Release 1.0.1

---

CHANGELOG.md
src/digitalmarketplace/components/list-input/_list-input.scss

Previously this was being overridden in the app, so I missed the alignment of the input number label was getting a little high on smaller screens.

Adjust position of List Input numbered label

---

.gitignore
CHANGELOG.md
README.md
package-lock.json
package.json
package/package.json
tasks/gulp/clean.js
tasks/gulp/copy.js

https://trello.com/c/fhL8Zl8T/175-3-unbundle-govuk-frontend-from-digitalmarketplace-govuk-frontend
We want to be able to use digitalmarketplace-govuk-frontend with [LandRegistry/govuk-frontend-jinja](https://github.com/LandRegistry/govuk-frontend-jinja) and reduce the coupling with [govuk-frontend](https://github.com/alphagov/govuk-frontend).
Local tests and the app are working.
There is a PR for the Briefs Frontend for an example of how to get a frontend app working with this change: https://github.com/alphagov/digitalmarketplace-briefs-frontend/pull/352

Unbundle govuk-frontend

---

CHANGELOG.md
package/package.json

💥 Breaking changes:
- GOV.UK Frontend has been removed from the package. [PR #173](https://github.com/alphagov/digitalmarketplace-govuk-frontend/pull/173)
- You will need to install GOV.UK Frontend separately - we recommend using (npm)](docs/installation/installing-with-npm.md).
- You should ensure that GOV.UK Frontend templates are loaded into your templating environment. If you are using v3, including `node_modules/govuk-frontend` should be sufficient. If you are using v2, you will need to prefix the templates with `govuk` to ensure they are correctly located.
- You should [add GOV.UK Frontend to your Sass load paths](https://frontend.design-system.service.gov.uk/importing-css-assets-and-javascript/#simplify-sass-import-paths). If you're using v2, you will have to make these available …

Release 2.0.0

---

python-tests/__snapshots__/test_templates.ambr
python-tests/test_templates.py
src/digitalmarketplace/components/alert/template.njk
src/digitalmarketplace/components/banner/template.njk

In Jinja dictsort would raise an exception if dictsort was being passed undefined, for instance when a param was not present.
This caused issues with alphagov/digitalmarketplace-briefs-frontend#354

Fix bug where Jinja dictsort would complain about undefined

---

src/digitalmarketplace/all.js
src/digitalmarketplace/all.scss
src/digitalmarketplace/components/option-select/README.md
src/digitalmarketplace/components/option-select/__snapshots__/template.test.js.snap
src/digitalmarketplace/components/option-select/_option-select.scss
src/digitalmarketplace/components/option-select/macro.njk
src/digitalmarketplace/components/option-select/option-select.js
src/digitalmarketplace/components/option-select/option-select.test.js
src/digitalmarketplace/components/option-select/option-select.yaml
src/digitalmarketplace/components/option-select/template.njk
src/digitalmarketplace/components/option-select/template.test.js

https://trello.com/c/VCANsToa/233-3-replace-search-filters-with-govuk-checkbox-groups-option-select
The Option Select component is heavily based on the Finder Frontend component: https://github.com/alphagov/finder-frontend/blob/master/app/views/components/_option-select.html.erb
It creates a collapsible container with checkboxes. If checkboxes are selected, a count is displayed and updated. We don't include the search text input from Finder.
Test this in operation by running this branch of the Buyer frontend locally: https://github.com/alphagov/digitalmarketplace-buyer-frontend/tree/bk-replace-filters-with-checkboxes

Adds Option Select component

---

CHANGELOG.md
src/digitalmarketplace/components/option-select/__snapshots__/template.test.js.snap
src/digitalmarketplace/components/option-select/option-select.yaml
src/digitalmarketplace/components/option-select/template.njk

Components should match govuk-frontend as much as possible, so let's switch the snake_case on Option Select params to camelCase.
This will need to be updated in the Buyer App when we bump the release of this package there.

Use camelCase on Option Select, not snake_case

---

CHANGELOG.md
src/digitalmarketplace/components/option-select/option-select.js

https://trello.com/c/AIVquUYj/1988-ccsrequests-re-g-cloud-12-filters-not-working
IE11 does not support `element.remove()`, so we can replace with `element.parentNode.removeChild(element)`
Tested on Browserstack and local Windows VM.

Fix IE11 option select bug

---

CHANGELOG.md
src/digitalmarketplace/all.scss
src/digitalmarketplace/components/attachment/README.md
src/digitalmarketplace/components/attachment/__snapshots__/template.test.js.snap
src/digitalmarketplace/components/attachment/_attachment.scss
src/digitalmarketplace/components/attachment/attachment.yaml
src/digitalmarketplace/components/attachment/macro.njk
src/digitalmarketplace/components/attachment/template.njk
src/digitalmarketplace/components/attachment/template.test.js

https://trello.com/c/jUpsvkxU/243-2-add-attachment-component-to-digital-marketplace-govuk-frontend
The component requires link information (title and href), but also supports optional information:
* file type
* file size
* number of pages
* contact email for alternative format
* custom html for alternative format
It is based on the [GOVUK Publishing Components Attachment](https://components.publishing.service.gov.uk/component-guide/attachment)
I've implemented the thumbnail by accounting explicitly for PDFs and CSVs which should cover the bulk of our documents. There is also a default thumbnail for any other doc types.
It's also possible to exclude the thumbnail altogether, for cases where we want to insert this component as text in a list or other contexts. In this case, the component …

Add attachment component

---

bin/release-to-branch.sh

Use `./bin/release-to-script.sh branch-name` to create the pre-release in a branch of your choosing; beware the script will delete pre-existing branches though!

Allow specifying branch name for pre-release script

---

CHANGELOG.md
src/digitalmarketplace/components/option-select/_option-select.scss

With the upgrade to govuk-frontend 3, we need to account for spacing/font differences in the `<h2>` tag.

Adjust spacing for option select header

---

package-lock.json
package.json

This PR changes our use of [standard](https://github.com/standard/standard) to [standardx](https://github.com/standard/standardx) for JS linting. This is to allow the editing of rules, specifically disabling the [no-var](https://eslint.org/docs/rules/no-var) rule.
Our components currently use `var` across the board to provide limited support to older browsers. While we'd prefer to update these to ES2015+, this is not a small amount of work. However, now that standard requires `let` or `const` over `var`, we are producing consistent warnings in our tests that will graduate to errors from standard 17+.
We're following the approach taken by govuk_publishing_components (https://github.com/alphagov/govuk_publishing_components/pull/1785) since it seems simple and sensible.

Replace standard with standardx

---

CHANGELOG.md
src/digitalmarketplace/components/attachment/__snapshots__/template.test.js.snap
src/digitalmarketplace/components/attachment/attachment.yaml
src/digitalmarketplace/components/attachment/template.njk
src/digitalmarketplace/components/attachment/template.test.js

On some of our existing document links, we have a short piece of text describing the document.
This PR adds a description to the Attachment component so we have somewhere to include this.

Add description to Attachment component

---

src/digitalmarketplace/components/attachment/__snapshots__/template.test.js.snap
src/digitalmarketplace/components/attachment/_attachment.scss
src/digitalmarketplace/components/attachment/attachment.yaml
src/digitalmarketplace/components/attachment/template.njk
src/digitalmarketplace/components/attachment/template.test.js

https://trello.com/c/tUd7Ck2w/275-5-replace-document-links-with-attachment-component-in-frontend-apps
This PR is a result of testing the Attachment component in real-life settings.
It adds the following enhancements:
* A custom tag for the link text - this defaults to `h2`
* Allows the "description" property to be either text or html
* Adds a "last updated" property to the available metadata properties
* Adds a slimline version of the component with a small thumbnail, for use in environments like table rows where space is at more of a premium. It's also still possible to use the text-only version of the component, but that's probably more suitable for use within bodies of text.
* Fixes a bug where the accessible format request details component would display even if no details had been …

Attachment component enhancements

---

CHANGELOG.md
package/package.json

- Attachments can have custom tags for link text [PR #233](https://github.com/alphagov/digitalmarketplace-govuk-frontend/pull/233)
- Adds a "last updated" property to attachments [PR #233](https://github.com/alphagov/digitalmarketplace-govuk-frontend/pull/233)
- Adds a slimline version of the attachment with a smaller thumbnail [PR #233](https://github.com/alphagov/digitalmarketplace-govuk-frontend/pull/233)
🔧 Fixes:
- Attachment accessible format details now do not display if not set [PR #233](https://github.com/alphagov/digitalmarketplace-govuk-frontend/pull/233)

Release 2.8.0

---

src/digitalmarketplace/components/attachment/__snapshots__/template.test.js.snap
src/digitalmarketplace/components/attachment/attachment.yaml
src/digitalmarketplace/components/attachment/template.njk
src/digitalmarketplace/components/attachment/template.test.js

One of our document links on the Buyer Frontend has an analytics event attached to it, and so needs some extra attributes. It's not difficult to see this being the case for other documents as well.
I missed this for the previous release, annoyingly, but it should also be released so it can be used on the Buyer Frontend app.

Add attributes to attachment link

---

src/digitalmarketplace/components/list-input/__snapshots__/template.test.js.snap
src/digitalmarketplace/components/list-input/list-input.test.js
src/digitalmarketplace/components/list-input/template.njk
src/digitalmarketplace/components/list-input/template.test.js

We want to be consistent with radios and checkboxes in govuk-frontend
v3, which also don't have a suffix for the first input [1].
[1]: https://github.com/alphagov/govuk-frontend/commit/e25b0e100298ca3ed758bfda3f312448d84ca229

Change first input in list input to have id without suffix

---

.nvmrc

We can save a bit of maintenance by pointing NVM to the LTS release to save having to keep updating for minor versions. This is consistent with the approach taken by PaaS team in 
https://github.com/alphagov/paas-admin/blob/bab335a9f7058b478a44565e424ed3c6074ef2d1/.nvmrc#L1

use lts codename for nvm version

---

CHANGELOG.md
package/package.json

🔧 Fixes:
- The header component now has the correct path for the fallback crown logo image [PR #283](https://github.com/alphagov/digitalmarketplace-govuk-frontend/pull/283)

Release 2.9.1

---

package-lock.json

We use [browserslist](https://github.com/browserslist/browserslist) to specify which browsers babel and autoprefixer should target, however that means [we have to update the `caniuse-lite` browser database regularly](https://github.com/browserslist/browserslist#browsers-data-updating).
It looks like this hasn't been done in a while, this PR does that by running `npx browserslist@latest --update-db`.

Bump caniuse-lite

---

.github/workflows/test.yml

Spotted this while looking at some Dependabot PRs.
We want to upgrade off Node 10 as soon as possible, ideally to Node 14.x which is the most recent LTS version. Add it to our pre-merge checks so we can see if we get any errors.

Run pre-merge checks on Node 14

---

.github/workflows/publish_package.yml

npm was failing to publish our packages for this repo because we were running `npm publish` in the repo directory rather than the package directory `./package`. This commit adds the correct working directory to the workflow step.

Fix publish package workflow

---

CHANGELOG.md
package/package.json

🔧 Fixes:
- The Node.js Package workflow now publishes to npm correctly (PRs [#303](https://github.com/alphagov/digitalmarketplace-govuk-frontend/pull/303), [#307](https://github.com/alphagov/digitalmarketplace-govuk-frontend/pull/307), [#308](https://github.com/alphagov/digitalmarketplace-govuk-frontend/pull/308))

Release 3.0.1

---

.github/workflows/publish_package.yml
.nvmrc
CHANGELOG.md
package/package.json

🔧 Fixes:
- The Node.js Package workflow now publishes to npm correctly (backports PRs [#303](https://github.com/alphagov/digitalmarketplace-govuk-frontend/pull/303), [#307](https://github.com/alphagov/digitalmarketplace-govuk-frontend/pull/307), [#308](https://github.com/alphagov/digitalmarketplace-govuk-frontend/pull/308))

Release 2.9.2

---

.github/workflows/publish_package.yml

We want to make sure releases to the 2.x.x series are not treated as the latest version by npm. We add a [dist-tag] to npm publish to do this; by supplying a tag to `npm publish` the default tag `latest` will not be applied.
We can make the change in this workflow file because when a GitHub Release is made from a commit, GitHub Actions will use the workflow file in that commit, so the main branch shouldn't have the `--tag` argument.
[dist-tag]: https://docs.npmjs.com/adding-dist-tags-to-packages

Add dist-tag govuk-frontend-2 to npm releases from this branch

---

README.md
docs/backporting.md

We are going to have to maintain the govuk-frontend-2 branch for a while, at least until supplier-frontend and admin-frontend are migrated to govuk-frontend 3.x.x, which will probably take a couple of quarters.
This commit adds some notes on how to do a backport release, for when we've made changes to the main branch of this repo and need those changes in the apps using the 2.x.x series.

Add docs on how to do backports

---

package-lock.json

Apply the result of running `npm audit fix` to take an updated version of the dependency that fixes [the issue](https://github.com/alphagov/digitalmarketplace-govuk-frontend/security/dependabot/package-lock.json/xmlhttprequest-ssl/open).
```
xmlhttprequest-ssl  <1.6.2
Severity: high
Arbitrary Code Injection - https://npmjs.com/advisories/1665
fix available via `npm audit fix`
node_modules/xmlhttprequest-ssl
engine.io-client  1.6.0 - 3.5.1 || 4.0.0-alpha.0 - 4.1.3
Depends on vulnerable versions of xmlhttprequest-ssl
node_modules/engine.io-client
2 high severity vulnerabilities
To address all issues, run:
npm audit fix
```

Fix vulnerability in xmlhttprequest-ssl

---

src/digitalmarketplace/components/attachment/__snapshots__/template.test.js.snap
src/digitalmarketplace/components/attachment/attachment.yaml

https://trello.com/c/UIQWRdCi/199-make-sure-helpdigitalmarketplaceservicegovuk-and-other-non-google-group-emails-start-continue-to-work
The previous example confused me - I didn't realise it was an example, and thought we were showing the non-existent 'help@' address to real users. Switch the example to match what we're really using in the apps. This should reduce the risk that people in future make the same mistake as I did.

Update example alternativeFormatContactEmail

---

CHANGELOG.md
src/digitalmarketplace/all.js
src/digitalmarketplace/all.scss
src/digitalmarketplace/components/new-framework-banner/README.md
src/digitalmarketplace/components/new-framework-banner/_new-framework-banner.scss
src/digitalmarketplace/components/new-framework-banner/macro.njk
src/digitalmarketplace/components/new-framework-banner/new-framework-banner.js
src/digitalmarketplace/components/new-framework-banner/new-framework-banner.yaml
src/digitalmarketplace/components/new-framework-banner/template.njk

- Add the HTML and css for the banner 
- Update change log
This is part of the ticket [OST-134](https://crowncommercialservice.atlassian.net/browse/OST-134)
Once this has been merged we will need to create a new release (2.10.0) and then update all the supplier-frontend app.
For the stylings and JavaScript, I got them from [govuk-frontend/notification-banner](https://github.com/alphagov/govuk-frontend/tree/a8bcd1379aedf3e057ea3eb7d606b91695b37c2a/src/govuk/components/notification-banner) and removed the parts we didn't need (just some CSS)

Make the banner component  for V2

---

CHANGELOG.md
package/package.json

🔧 Fixes:
- Remove email from URL sent to Google Analytics for an edge case [PR #493](https://github.com/Crown-Commercial-Service/digitalmarketplace-govuk-frontend/pull/493)

Release 3.1.2

---

CHANGELOG.md
package/package.json

🔧 Fixes:
- Remove email from URL sent to Google Analytics for an edge case [PR #493](https://github.com/Crown-Commercial-Service/digitalmarketplace-govuk-frontend/pull/494)

Release 2.10.2

---

python-tests/__snapshots__/test_templates.ambr
src/digitalmarketplace/components/footer/__snapshots__/template.test.js.snap
src/digitalmarketplace/components/footer/template.njk

As requested via the zen/help-desk, modifications to the footer links were required. As described in the ticket; the 'Applying to sell on the DOS framework' link should point to the new DOS 6 page https://www.gov.uk/guidance/how-to-apply-to-sell-on-the-digital-outcomes-framework
With correct permissions, see ticket:
https://crowncommercial.zendesk.com/agent/tickets/34497

Zendesk Requests to remove or update links

---

python-tests/__snapshots__/test_templates.ambr
src/digitalmarketplace/components/footer/__snapshots__/template.test.js.snap
src/digitalmarketplace/components/footer/template.njk

As requested via the zen/help-desk, modifications to the footer links were required. As described in the ticket; the 'Applying to sell on the DOS framework' link should point to the new DOS 6 page https://www.gov.uk/guidance/how-to-apply-to-sell-on-the-digital-outcomes-framework
With correct permissions, see ticket:
https://crowncommercial.zendesk.com/agent/tickets/34497

Update footer link, for frontend apps

---

CHANGELOG.md
src/digitalmarketplace/components/new-framework-banner/template.njk

Updates the banner to reflect the new G13 wording, as DOS6 is now obsolete in this regard.

OST-509-Updates-Banner-Text

---

CHANGELOG.md
src/digitalmarketplace/components/new-framework-banner/template.njk

(V2) Updates the banner to reflect the new G13 wording, as DOS6 is now obsolete in this regard.

OST-509-Updates-Banner-Text-V2

---

CHANGELOG.md
package/package.json

🔧 Fixes:
- Updates banner text [PR #531](https://github.com/Crown-Commercial-Service/digitalmarketplace-govuk-frontend/pull/531)
🔧 Fixes:
- Skip this version, as it already exists in npm, causing a 400 error on publish.

Release-3.1.5

---

CHANGELOG.md
package/package.json

🔧 Fixes:
- Updates banner text [PR #533](https://github.com/Crown-Commercial-Service/digitalmarketplace-govuk-frontend/pull/533)
🔧 Fixes:
- Skip this version, as it already exists in npm, causing a 400 error on publish.

Release-2.10.5

---

CHANGELOG.md
package/package.json

🔧 Fixes:
- Update Banner helper text, for DMP 1.5 [PR #638](https://github.com/Crown-Commercial-Service/ccs-digitalmarketplace-govuk-frontend/pull/638)

release-3.1.6

---

CHANGELOG.md
package/package.json
src/digitalmarketplace/components/new-framework-banner/template.njk

🔧 Fixes:
- Update Banner helper text, for DMP 1.5 [PR #640](https://github.com/Crown-Commercial-Service/ccs-digitalmarketplace-govuk-frontend/pull/640)

Release 2.10.6

---

CHANGELOG.md
package/package.json
src/digitalmarketplace/components/new-framework-banner/template.njk

🔧 Fixes:
- Update Banner helper text once again, for DMP 1.5 [PR #671](https://github.com/Crown-Commercial-Service/ccs-digitalmarketplace-govuk-frontend/pull/671)
Request from Zendesk: https://crowncommercial.zendesk.com/agent/tickets/42767

Release 3.1.8

---

CHANGELOG.md
package/package.json
src/digitalmarketplace/components/new-framework-banner/template.njk

🔧 Fixes:
- Update Banner helper text, for DMP 1.5 [PR #672](https://github.com/Crown-Commercial-Service/ccs-digitalmarketplace-govuk-frontend/pull/672)
Request from Zendesk: https://crowncommercial.zendesk.com/agent/tickets/42767

Release 2.10.9

---

CHANGELOG.md
package-lock.json
package/package.json

🔧 Changes:
- Update Banner text to ask to show G-Cloud 13 is live [PR #700](https://github.com/Crown-Commercial-Service/digitalmarketplace-govuk-frontend/pull/700)

Release 3.10.0

---

CHANGELOG.md
package/package.json

🔧 Changes:
- Update Banner text to ask to show G-Cloud 13 is live [PR #701](https://github.com/Crown-Commercial-Service/digitalmarketplace-govuk-frontend/pull/701)

Release 2.11.0

---

src/digitalmarketplace/components/new-framework-banner/macro.njk
src/digitalmarketplace/components/new-framework-banner/new-framework-banner.yaml
src/digitalmarketplace/components/new-framework-banner/template.njk

Ticket: [OST-583](https://crowncommercialservice.atlassian.net/browse/OST-583)
This is what it will look like:
I've added a conditional param to only show the new banner if there is a live G-Cloud framework. Otherwise it shows the banner in [OST-574](https://crowncommercialservice.atlassian.net/browse/OST-574).

OST-583 - Update the banner, yet again

---

CHANGELOG.md
package/package.json

🔧 Changes:
- Update Banner text again to warn of G-Cloud 12 closing [PR #705](https://github.com/Crown-Commercial-Service/digitalmarketplace-govuk-frontend/pull/705)

Release 2.12.0

---

CHANGELOG.md
package/package.json

🔧 Changes:
- Update Banner text again to warn of G-Cloud 12 closing [PR #704](https://github.com/Crown-Commercial-Service/digitalmarketplace-govuk-frontend/pull/704)

Release 3.11.0

---

src/digitalmarketplace/components/new-framework-banner/template.njk

Update the banner to signal that DOS6 is live

---

CHANGELOG.md
package/package.json

🔧 Changes:
- Update Banner text again to notify that DOS6 and G-Cloud 13 are live [PR #726](https://github.com/Crown-Commercial-Service/digitalmarketplace-govuk-frontend/pull/726)

Release 3.11.1

---

CHANGELOG.md
package/package.json

🔧 Changes:
- Update Banner text again to notify that DOS6 and G-Cloud 13 are live [PR #727](https://github.com/Crown-Commercial-Service/digitalmarketplace-govuk-frontend/pull/727)

Release 2.12.1

---

src/digitalmarketplace/components/new-framework-banner/template.njk

Update the banner to include the DOS5 closing dates.
Here is the banner:

Update the banner to include the DOS5 closing dates

---

src/digitalmarketplace/components/new-framework-banner/template.njk

Update the banner to include the DOS5 closing dates.
Here is the banner:

Update the banner to include the DOS5 closing dates - V2

---

CHANGELOG.md
package/package.json

🔧 Changes:
- Update Banner text again to notify that DOS5 is closing [PR #732](https://github.com/Crown-Commercial-Service/digitalmarketplace-govuk-frontend/pull/732)

Release 2.12.2

---

CHANGELOG.md
package/package.json

🔧 Changes:
- Update Banner text again to notify that DOS5 is closing [PR #733](https://github.com/Crown-Commercial-Service/digitalmarketplace-govuk-frontend/pull/733)

Release 3.11.2

---

CHANGELOG.md
package/package.json

🔧 Changes:
- Update Banner text again to say the date that DOS5 is closing [PR #758](https://github.com/Crown-Commercial-Service/digitalmarketplace-govuk-frontend/pull/758)

Release 2.12.3

---

CHANGELOG.md
package/package.json

🚧 Fixes:
- Add Google Tag Manager for DMP 1.0 [PR #789](https://github.com/Crown-Commercial-Service/digitalmarketplace-govuk-frontend/pull/789)

Release 2.13.0

---

CHANGELOG.md
package/package.json

🚧 Fixes:
- Add Google Tag Manager for DMP 1.0 [PR #788](https://github.com/Crown-Commercial-Service/digitalmarketplace-govuk-frontend/pull/788)

Release 3.12.0
