Crown-Commercial-Service/digitalmarketplace-govuk-frontend

tasks/gulp/build.js, tasks/gulp/clean.js
Example.
```
[13:47:14] 📁  - Deleted files and directories:
/Users/alistairlaing/work/dmp/dmp-frontend/package/govuk-frontend
[13:47:14] 📋  - Copying GOV.UK Frontend to package directory
[13:47:14] Copied node_modules/govuk-frontend
[13:47:14] Copied node_modules/govuk-frontend/README.md
[13:47:14] Copied node_modules/govuk-frontend/all-ie8.scss
[13:47:14] Copied node_modules/govuk-frontend/all.js
[13:47:14] Copied node_modules/govuk-frontend/all.scss
[13:47:14] Copied node_modules/govuk-frontend/assets
```
=> Style logs to improve readability

README.md, docs/installation/updating-with-npm.md
This is a very basic README file that will be fleshed out further as we start to use the npm module.
- Install instructions
- Local development process (building custom components)
- Coding standards
Ticket: https://trello.com/c/KBZFQOfK
=> Add README.md

CHANGELOG.md, bin/pre-release.sh, bin/release.sh, docs/CHANGELOG_TEMPLATE.md, docs/publishing.md, gulpfile.js, package.json, package/.gitignore, package/package.json
This PR will enable us to publish digitalmarketplace-govuk-frontend to npm. I have also tried to document the steps that we will follow to publish a release.
I did try to follow and reuse most of [govuk-frontend's](https://github.com/alphagov/govuk-frontend) process
Ticket :https://trello.com/c/KBZFQOfK
=> Scripts and documentation to release to npmjs.org

README.md, docs/installation/updating-with-npm.md
Fixes some minor issues which @katstevens identified in #5.
=> Fix minor issues in README and Update docs

bin/release.sh
Fixes issue where script would exit early even where --dry-run flag was
not provided.
=> Fix bug with release script

bin/release-to-branch.sh, docs/publishing-a-pre-release.md, package.json
Content/code inspired and re-used from GOV.UK Frontend
https://github.com/alphagov/govuk-frontend/blob/master/docs/contributing/publishing-a-pre-release.md
https://github.com/alphagov/govuk-frontend/blob/master/bin/release-to-branch.sh
=> Add release to branch feature.

package-lock.json, package.json, src/digitalmarketplace/templates/layouts/_custom_dimensions.html, src/digitalmarketplace/templates/layouts/_custom_dimensions.test.js, src/digitalmarketplace/templates/layouts/_site_verification.html, src/digitalmarketplace/templates/layouts/_site_verification.test.js, tasks/gulp/build.js
This originally came from the DM toolkit. As govuk-frontend does not offer
these two features this commit copied the contents from DM toolkit.
=> Add site verification and custom dimension tracking

CHANGELOG.md
Should have been added as part of #15
=> Adds CHANGELOG entry

.github/workflows/nodejs.yml, .travis.yml
=> Github Actions CI

CHANGELOG.md, package.json, package/package.json
- Add error templates
Error templates which use GOV.UK Frontend classes for styling.
([PR #14](https://github.com/alphagov/digitalmarketplace-govuk-frontend/pull/14))
- Add site verification and custom dimension tracking
This originally originally built into `digitalmarketplace-frontend-toolkit` and will
be needed in the future when we do away with `digitalmarketplace-frontend-toolkit`.
([PR #15](https://github.com/alphagov/digitalmarketplace-govuk-frontend/pull/15))
=> Release v0.2.0

app/app.js, app/assets/scss/app.scss, src/digitalmarketplace/components/footer/__snapshots__/template.test.js.snap, src/digitalmarketplace/components/footer/template.njk
Ticket: https://trello.com/c/lXpy2vZH/142-3-change-footer-to-use-two-column-layout-in-digitalmarketplace-frontend-toolkit-and-all-frontend-apps
Sister pull request to alphagov/digitalmarketplace-frontend-toolkit#489
=> Change layout of footer links

CHANGELOG.md, package/package.json
- New component: Digital Marketplace Header component
*Requirement before using this component:*
- To use this the application must be using `govuk-frontend` template
- To use this the application must be using `govuk-frontend` phase banner as phase tag
is no longer part of the header and sits underneath and outside the header
*Installing component:*
1. Check config.py has this line for jinja to find the components
```
os.path.join(repo_root, 'node_modules', 'digitalmarketplace-govuk-frontend')
```
2. Import the component in `_base_page.html`
`{% from "digitalmarketplace/components/header/macro.njk" import dmheader %}`
3. Use the component `{{ dmHeader({}) }}`
([PR #25](https://github.com/alphagov/digitalmarketplace-govuk-frontend/pull/25))
- New component: Digital …
=> Release v0.3.0 - NEW COMPONENTS - Header & Footer

CHANGELOG.md, package/package.json
- New component: Digital Marketplace Alert component
*Installing component:*
1. Check config.py has this line for jinja to find the components
```
os.path.join(repo_root, 'node_modules', 'digitalmarketplace-govuk-frontend')
```
2. Import the component in `_base_page.html`
`{% from "digitalmarketplace/components/alert/macro.njk" import dmAlert %}`
3. Use the component `{{ dmAlert({...}) }}`. For its parameters, see its README and/or YAML. For examples, see the review app.
([PR #45](https://github.com/alphagov/digitalmarketplace-govuk-frontend/pull/45))
=> Release 0.4.0

README.md, docs/publishing.md
Fixes/adds some things that I thought could be improved whilst following them.
=> Some updates to the publising docs

.babelrc, CHANGELOG.md, app/app.js, app/views/layouts/_generic.njk, bin/release-to-branch.sh, bin/release.sh, gulpfile.js, jest-puppeteer.config.js, package-lock.json, package.json, src/digitalmarketplace/_all.scss, src/digitalmarketplace/all.js, src/digitalmarketplace/components/alert/template.test.js, src/digitalmarketplace/components/analytics/analytics.js, src/digitalmarketplace/components/analytics/analytics.test.js, src/digitalmarketplace/components/analytics/init.js, src/digitalmarketplace/components/analytics/init.test.js, src/digitalmarketplace/components/cookie-banner/README.md, src/digitalmarketplace/components/cookie-banner/__snapshots__/template.test.js.snap, src/digitalmarketplace/components/cookie-banner/_cookie-banner.scss, src/digitalmarketplace/components/cookie-banner/cookie-banner.js, src/digitalmarketplace/components/cookie-banner/cookie-banner.test.js, src/digitalmarketplace/components/cookie-banner/cookie-banner.yaml, src/digitalmarketplace/components/cookie-banner/macro.njk, src/digitalmarketplace/components/cookie-banner/template.njk, src/digitalmarketplace/components/cookie-banner/template.test.js, src/digitalmarketplace/components/footer/template.test.js, src/digitalmarketplace/components/header/template.test.js, src/digitalmarketplace/helpers/cookie/cookie-functions.js, tasks/gulp/compile-assets.js
Ticket: https://trello.com/c/r9YH2CFD/242-3-add-cookie-banner-component-to-digital-marketplace-govuk-frontend
Based on [Notify](https://github.com/alphagov/notifications-admin/pull/3238) & GOV.UK Cookie banner
Re-introduces Analytics code - this will be disabled by default.
Cookie Settings page JS and tests will be added in a separate PR, based on this one (https://github.com/alphagov/digitalmarketplace-govuk-frontend/pull/57).
=> New Cookie Component: 

CHANGELOG.md, package/package.json
New component: Cookie banner and analytics
*Requirement before using this component:*
- To use this the application must be using `govuk-frontend` template
- There must be functionality for the user to change their cookie preferences
*Installing component:*
1. Check config.py has this line for jinja to find the components
```
os.path.join(repo_root, 'node_modules', 'digitalmarketplace-govuk-frontend')
```
2. Import the component in `_base_page.html`
```
{% from "digitalmarketplace/components/cookie-banner/macro.njk" import dmCookieBanner %}
```
3. Include the component `{{ dmCookieBanner({...}) }}` in the `{% block header %}` block.
For its parameters, see its README and/or YAML. For examples, see the review app.
([PR …
=> Release 0.5.0

CHANGELOG.md, package/package.json
🔧 Fixes:
- Initialise Analytics if consent cookie is present.
=> Release 0.6.3

CHANGELOG.md, package/package.json
🔧 Fixes:
- Remove Google Analytics tracker name.
=> Release 0.6.4

CHANGELOG.md, package/package.json
🔧 Fixes:
- Fix typo in footer. ([PR #79](https://github.com/alphagov/digitalmarketplace-govuk-frontend/pull/79))
- Fix margin right for buttons in cookie banner ([PR #78](https://github.com/alphagov/digitalmarketplace-govuk-frontend/pull/78))
=> Release 0.6.5

Procfile, app/views/layouts/_generic.njk, app/views/layouts/index.njk, app/views/partials/code.njk, docs/deploying/heroku.md, gulpfile.js, package.json
Add support for deploying the review app to Heroku.
You can see it in action at https://dmp-govuk-frontend-review.herokuapp.com
=> Add Heroku support

CHANGELOG.md, package/package.json
🔧 Fixes:
- Deletes cross domain tracking cookie (along with other analytics cookies) when the user changes their preferences.
- Adds test coverage for cookie helper functions
=> Release 0.8.1

package-lock.json
https://trello.com/c/JNW4K4vr/1618-vulnerability-fix-tracking
Results of running the automated `npm audit fix` on `package-lock.json`, which addresses the vulnerability for `minimist`.
=> Upgrade minimist package with npm audit fix

CHANGELOG.md, package/package.json
- Representative usage examples for the banner component [PR #114](https://github.com/alphagov/digitalmarketplace-govuk-frontend/pull/114).
🔧 Fixes:
- Add ARIA roles and labels to alert and banner components [PR #113](https://github.com/alphagov/digitalmarketplace-govuk-frontend/pull/113)
- Adjust tabindex attribute on alert and banner components [PR #113](https://github.com/alphagov/digitalmarketplace-govuk-frontend/pull/113)
- Fix mismatched tags in the banner component [PR #114](https://github.com/alphagov/digitalmarketplace-govuk-frontend/pull/114).
- Ensure links are readable in the banner component [PR #114](https://github.com/alphagov/digitalmarketplace-govuk-frontend/pull/114).
=> Release 0.9.0

CHANGELOG.md, package/package.json
🔧 Fixes:
- Javascript to support error message on cookie settings page [PR #124](https://github.com/alphagov/digitalmarketplace-govuk-frontend/pull/124)
=> release 0.9.1

README.md, app/views/macros/showExamples.njk, lib/jest-helpers.js
A few tweaks to improve the app:
* Updated README
* Add ability to wrap components with `<main>`
* Add title to iFrames
* Fix "open in new tab" links
=> App improvements

CHANGELOG.md, app/app.js, app/views/partials/banner.njk, package-lock.json, package.json, src/digitalmarketplace/components/banner/_banner.scss, src/digitalmarketplace/components/cookie-banner/__snapshots__/template.test.js.snap, src/digitalmarketplace/components/cookie-banner/template.njk, src/digitalmarketplace/components/footer/__snapshots__/template.test.js.snap, src/digitalmarketplace/components/header/__snapshots__/template.test.js.snap, src/digitalmarketplace/components/list-input/__snapshots__/template.test.js.snap
Part of https://trello.com/c/5FhjhxMd/139-3-migrate-user-frontend-to-govuk-frontend-v3
=> Update govuk-frontend from V2 to V3

CHANGELOG.md, src/digitalmarketplace/components/list-input/__snapshots__/template.test.js.snap, src/digitalmarketplace/components/list-input/_list-input.scss, src/digitalmarketplace/components/list-input/list-input.test.js, src/digitalmarketplace/components/list-input/list-input.yaml, src/digitalmarketplace/components/list-input/template.njk, src/digitalmarketplace/components/list-input/template.test.js
https://trello.com/c/VG4caYdJ/136-3-replace-list-form-with-list-input-component-in-create-a-dos-opportunity-journey
Now that we're testing this component "in the wild", there are some quirks that needed to be dealt with.
* Simplifed some fieldset properties
* Added ability to pass in `question_advice`
* Added an itemLabelPrefix property to enable friendlier labels on inputs.
* Append `-1` to first input to conform with our Errors
=> List Input updates to work better on Briefs Frontend

CHANGELOG.md, package/package.json
- You can now use the parameter `question_advice` with the list input component to show question advice to the user [PR #163](https://github.com/alphagov/digitalmarketplace-govuk-frontend/pull/163)
- You can now use the parameter `itemLabelPrefix` with the list input component to add a visually hidden label to inputs [PR #163](https://github.com/alphagov/digitalmarketplace-govuk-frontend/pull/163)
🔧 Fixes:
- The list input component now has simpler fieldset properties [PR #163](https://github.com/alphagov/digitalmarketplace-govuk-frontend/pull/163)
- The list input component now has the first input id end in `-1` as expected by the content loader [PR #163](https://github.com/alphagov/digitalmarketplace-govuk-frontend/pull/163)
=> Release 1.1.0

CHANGELOG.md, package/package.json
🔧 Fixes:
- The list input component input label numbers now align properly on smaller screens [PR #168](https://github.com/alphagov/digitalmarketplace-govuk-frontend/pull/168)
=> Release 1.1.1

CHANGELOG.md, README.md, src/digitalmarketplace/components/alert/_alert.scss, src/digitalmarketplace/components/alert/macro.njk, src/digitalmarketplace/components/banner/_banner.scss, src/digitalmarketplace/components/banner/macro.njk, src/digitalmarketplace/components/cookie-banner/_cookie-banner.scss, src/digitalmarketplace/components/cookie-banner/macro.njk, src/digitalmarketplace/components/footer/macro.njk, src/digitalmarketplace/components/footer/template.njk, src/digitalmarketplace/components/header/_header.scss, src/digitalmarketplace/components/header/macro.njk, src/digitalmarketplace/components/header/template.njk, src/digitalmarketplace/components/list-input/_list-input.scss, src/digitalmarketplace/components/list-input/macro.njk, src/digitalmarketplace/components/list-input/template.njk
trello: https://trello.com/c/aYlQvPAJ/174-2-remove-relative-imports-from-macro-files-in-digitalmarketplace-govuk-frontend
=> 174 2 remove relative imports from macro files in digitalmarketplace govuk frontend

CHANGELOG.md, src/digitalmarketplace/components/footer/__snapshots__/template.test.js.snap, src/digitalmarketplace/components/footer/template.njk, src/digitalmarketplace/components/footer/template.test.js
https://trello.com/c/rRLFjASj/240-publish-accessibility-statement-by-wednesday
This adds a link to the accessibility statement on the footer component
=> Add accessibility statement link to footer

CHANGELOG.md, package/package.json
- Footer component now contains link to accessibility statement [PR #180](https://github.com/alphagov/digitalmarketplace-govuk-frontend/pull/180)
=> Release 2.1.0

CHANGELOG.md, package/package.json
- New component: Digital Marketplace Option Select component
- Use the component `{{ dmOptionSelect({...}) }}`. For its parameters, see its README and/or YAML. For examples, see the review app. [PR #183](https://github.com/alphagov/digitalmarketplace-govuk-frontend/pull/183)
=> Release 2.2.0

CHANGELOG.md, package/package.json
- New component: Digital Marketplace Search Box component
- Use the component `{{ dmSearchBox({...}) }}`. For its parameters, see its README and/or YAML. For examples, see the review app. [PR #185](https://github.com/alphagov/digitalmarketplace-govuk-frontend/pull/185)
🔧 Fixes:
- Option Select now uses camelCase instead of snake_case to match govuk-frontend [PR #187](https://github.com/alphagov/digitalmarketplace-govuk-frontend/pull/187)
=> Release v2.3.0

CHANGELOG.md, src/digitalmarketplace/all.scss, src/digitalmarketplace/components/previous-next-pagination/__snapshots__/template.test.js.snap, src/digitalmarketplace/components/previous-next-pagination/_previous-next-pagination.scss, src/digitalmarketplace/components/previous-next-pagination/macro.njk, src/digitalmarketplace/components/previous-next-pagination/previous-next-pagination.yaml, src/digitalmarketplace/components/previous-next-pagination/template.njk, src/digitalmarketplace/components/previous-next-pagination/template.test.js
https://trello.com/c/d1wSRrnT/179-2-use-govuk-style-for-previous-and-next-links-on-search-results-page
=> Add previous/next pagination

CHANGELOG.md, package/package.json
- New component: Digital Marketplace Previous Next Pagination component
- Use the component `{{ dmPreviousNextPagination({...}) }}`. For its parameters, see its README and/or YAML. For examples, see the review app. [PR #189](https://github.com/alphagov/digitalmarketplace-govuk-frontend/pull/189)
=> Release v2.4.0

CHANGELOG.md, package/package.json
🔧 Fixes:
- Option Select now works properly in IE11. [PR #193](https://github.com/alphagov/digitalmarketplace-govuk-frontend/pull/193)
=> Release v2.4.1

CHANGELOG.md, package/package.json
- New component: Digital Marketplace Attachment component
- Use the component `{{ dmAttachment({...}) }}`. For its parameters, see its README and/or YAML. For examples, see the review app. [PR #200](https://github.com/alphagov/digitalmarketplace-govuk-frontend/pull/200)
=> Release v2.5.0

CHANGELOG.md, app/app.js, lib/helper-functions.js, src/digitalmarketplace/components/header/__snapshots__/template.test.js.snap, src/digitalmarketplace/components/header/header.yaml, src/digitalmarketplace/components/header/template.njk, src/digitalmarketplace/components/header/template.test.js, src/digitalmarketplace/components/list-input/list-input.test.js, src/digitalmarketplace/components/previous-next-pagination/template.test.js
https://trello.com/c/N0tUjqnr/265-2-set-active-styles-on-header-nav-links
Allows the use of the `active` param to set which link, if any, should be active.
```
{{ dmHeader({
"role": "supplier",
"active": "/help"
})}}
```
=> Add active links to Header component

README.md
=> Update README.md to detail how to install with npm

CHANGELOG.md, package/package.json
- The Header component now supports active nav items [PR #207](https://github.com/alphagov/digitalmarketplace-govuk-frontend/pull/207)
- The current active path can be passed into the component call:
```
{{ dmHeader({
"role": "supplier",
"active": request.path
})}}
```
=> Release v2.6.0

CHANGELOG.md, package/package.json
- A description can now be added to the Attachment component [PR #230](https://github.com/alphagov/digitalmarketplace-govuk-frontend/pull/230)
=> Release v2.7.0

CHANGELOG.md, package/package.json
- Attachments links can have custom attributes [PR #235](https://github.com/alphagov/digitalmarketplace-govuk-frontend/pull/235)
=> Release 2.9.0

CHANGELOG.md, package/package.json
Once this is approved and merged I will make a pre-release branch called `pre-release-3.0.0-govuk-frontend-3-r4` using the script.
=> Release 3.0.0-govuk-frontend-3-r4

.github/workflows/test.yml, .travis.yml
https://trello.com/c/cnNEUjhz/2126-epic-migrate-travis-ci-usages-to-github-actions
=> migrate tests to Github Actions

.github/workflows/publish_package.yml, docs/publishing.md
https://trello.com/c/HSgxGzle/762-05-publish-digitalmarketplace-gov-uk-frontend-using-github-actions
=> publish package using github actions

.github/workflows/test.yml
https://trello.com/c/0BmkYFSD/907-3-node-10-is-eol-april-2021-upgrade-node-to-v14
=> only test on Node 14.x to reflect production environment

.github/workflows/publish_package.yml, .nvmrc, package/package.json
https://trello.com/c/0BmkYFSD/907-3-node-10-is-eol-april-2021-upgrade-node-to-v14
=> use Node 14 LTS

.github/workflows/publish_package.yml, package/package.json
fix following https://github.com/alphagov/digitalmarketplace-govuk-frontend/pull/298 Github Actions failure﻿
=> fix run command and bump version

.github/workflows/publish_package.yml, package/package.json
bug fix after #305 and bump version
=> fix nvm install

.github/workflows/publish_package.yml, package/package.json
Hardcode node version for now as we've hit multiple issues trying to derive it in this case.
=> Hardcode Node version

src/digitalmarketplace/components/new-framework-banner/README.md, src/digitalmarketplace/components/new-framework-banner/macro.njk, src/digitalmarketplace/components/new-framework-banner/new-framework-banner.yaml, src/digitalmarketplace/components/new-framework-banner/template.njk
- Make the banner component
- Add example and README for the component
This is part of the ticket [OST-134](https://crowncommercialservice.atlassian.net/browse/OST-134) (2/5)
Once this has been merged we will need to create a new release (3.1.0) and then update all the frontend apps that use this package.
=> Make the banner component

CHANGELOG.md, package/package.json
- Add banner component with directions to apply to new DMP framework [PR #474](https://github.com/Crown-Commercial-Service/digitalmarketplace-govuk-frontend/pull/474)
=> Release 3.1.0

CHANGELOG.md, package/package.json
- Add banner component with directions to apply to new DMP framework PR #480
=> Release 2.10.0

package/package.json, src/digitalmarketplace/components/new-framework-banner/template.njk
See comments in [OST-134](https://crowncommercialservice.atlassian.net/browse/OST-134)
=> Fix typo from "information" to "applications"

src/digitalmarketplace/components/analytics/analytics.test.js, src/digitalmarketplace/components/analytics/pii.js
This is required for supplier-frontend
See https://github.com/Crown-Commercial-Service/digitalmarketplace-govuk-frontend/pull/493 for details
=> Prevent emails in URL

CHANGELOG.md, package/package.json
🔧 Fixes:
- Updates footer link [PR #523](https://github.com/Crown-Commercial-Service/digitalmarketplace-govuk-frontend/pull/523)
=> update changelog and version, for a release

package/package.json
🔧 Fixes:
- Updates banner text to reflect G13 [PR #531](https://github.com/Crown-Commercial-Service/digitalmarketplace-govuk-frontend/pull/531)
=> Updates version and release to npm

package/package.json
🔧 Fixes:
- Updates banner text [PR #533](https://github.com/Crown-Commercial-Service/digitalmarketplace-govuk-frontend/pull/533)
=> Release-2.10.4

src/digitalmarketplace/components/new-framework-banner/template.njk
Request from zendesk: https://crowncommercial.zendesk.com/agent/tickets/41811
The banner will now look like:
=> V2 MASTER - Update notification banner for changes on 26/08/2022

src/digitalmarketplace/components/new-framework-banner/template.njk
Ticket: [SCAT-7353](https://crowncommercialservice.atlassian.net/browse/SCAT-7353)
=> SCAT-7353 - Update the banner text with directions to PPG

CHANGELOG.md, package-lock.json, package/package.json
🔧 Changes:
- Update Banner text to ask buyers to sign up with PPG, for DMP 1.0 [PR #690](https://github.com/Crown-Commercial-Service/digitalmarketplace-govuk-frontend/pull/690)
=> Release 3.1.9

src/digitalmarketplace/components/new-framework-banner/template.njk
Ticket: [OST-574](https://crowncommercialservice.atlassian.net/browse/OST-574)
=> OST-574 - Update the banner text

src/digitalmarketplace/components/new-framework-banner/template.njk
=> Update the banner to signal that DOS6 is live

src/digitalmarketplace/components/new-framework-banner/template.njk
=> Update the banner to announce DOS5 closure

src/digitalmarketplace/components/analytics/init.js, src/digitalmarketplace/components/analytics/tagManager.js, src/digitalmarketplace/components/cookie-banner/cookie-banner.test.js, src/digitalmarketplace/helpers/cookie/cookie-functions.js, src/digitalmarketplace/helpers/cookie/cookie-functions.test.js
Add the google tag manager code
Add JS Cookie to make working with cookies much easer which helps went managing GTM cookies
=> Add the GTM script

src/digitalmarketplace/components/analytics/init.js, src/digitalmarketplace/components/analytics/tagManager.js, src/digitalmarketplace/components/cookie-banner/cookie-banner.test.js, src/digitalmarketplace/helpers/cookie/cookie-functions.js, src/digitalmarketplace/helpers/cookie/cookie-functions.test.js
Add the google tag manager code
Add JS Cookie to make working with cookies much easer which helps went managing GTM cookies
=> Add the GTM scrip
